version: '3'
services:
  #PHP Service
  app:
    image: node:15-alpine3.10
    container_name: app_${DOCKER_NAME}
    restart: unless-stopped
    #command: bash /scripts/init.sh
    entrypoint: sh /scripts/init.sh
    tty: true
    working_dir: /app
    volumes:
      - ${PROJECT_PATH}:/app
      - ${DOCKER_PATH}/node/init.sh:/scripts/init.sh
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
